# Generated by Django 5.0 on 2023-12-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('change_percent', models.CharField(max_length=30)),
            ],
        ),
    ]
